using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: ExportFont("fa-brands-400.ttf", Alias = "FontAwesomeBrands")]
[assembly: ExportFont("fa-regular-400.ttf", Alias = "FontAwesomeRegular")]
[assembly: ExportFont("fa-solid-900.ttf", Alias = "FontAwesomeSolid")]
[assembly: ExportFont("Nunito-Black.ttf", Alias = "NunitoBlack")]
[assembly: ExportFont("Nunito-BlackItalic.ttf", Alias = "NunitoBlackItalic")]
[assembly: ExportFont("Nunito-Bold.ttf", Alias = "NunitoBold")]
[assembly: ExportFont("Nunito-BoldItalic.ttf", Alias = "NunitoBoldItalic")]
[assembly: ExportFont("Nunito-ExtraBold.ttf", Alias = "NunitoExtraBold")]
[assembly: ExportFont("Nunito-ExtraBoldItalic.ttf", Alias = "NunitoExtraBoldItalic")]
[assembly: ExportFont("Nunito-ExtraLight.ttf", Alias = "NunitoExtraLight")]
[assembly: ExportFont("Nunito-ExtraLightItalic.ttf", Alias = "NunitoExtraLightItalic")]
[assembly: ExportFont("Nunito-Italic.ttf", Alias = "NunitoItalic")]
[assembly: ExportFont("Nunito-Light.ttf", Alias = "NunitoLight")]
[assembly: ExportFont("Nunito-LightItalic.ttf", Alias = "NunitoLightItalic")]
[assembly: ExportFont("Nunito-Medium.ttf", Alias = "NunitoMedium")]
[assembly: ExportFont("Nunito-MediumItalic.ttf", Alias = "Nunito-MediumItalic")]
[assembly: ExportFont("Nunito-Regular.ttf", Alias = "NunitoRegular")]
[assembly: ExportFont("Nunito-SemiBold.ttf", Alias = "NunitoSemiBold")]
[assembly: ExportFont("Nunito-SemiBoldItalic.ttf", Alias = "NunitoSemiBoldItalic")]
[assembly: ExportFont("NewYorkSmall-Bold.ttf", Alias = "NewYorkSmallBold")]